### PR TITLE
add a background to the bsod i guess

### PR DESCRIPTION
**Pull request by markverb1**

### CODE REVIEW

**Comment by markverb1** [comment]
how do i add stuff

**Comment by xemonix0** [comment]
> how do i add stuff

idk xd

**Comment by markverb1** [comment]
> > how do i add stuff
> 
> idk xd

it doesn't matter i figured it out

**Comment by markverb1** [comment]
also when will you merge :trollface:

**Review by xemonix0 — APPROVED** [review]
Thanks, approved! Will improve after merging.

**Pull request merged**
